language: go
go:
  - 1.8
  - tip
script:
  - go test -race -v -bench=. ./...
notifications:
  email: false
env:
  # todo: support okq somehow
  - POSTMASTER_SENDGRID_KEY="test"
services:
  - mongodb
  - redis-server
before_install:
  - go get -u github.com/mc0/okq
before_script:
  - |
    okq &
    OKQ_PID=$!
after_script:
  - kill $OKQ_PID
